
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
#  config:
#    import: 'aws-parameterstore:'
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://rds-pre-029.cnuf9an3lpvk.ap-northeast-2.rds.amazonaws.com:13306/test
      url: jdbc:h2:mem:test
  #    username: admin
  #    password: Eulja2013*
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

  #spring Oauth2 ?? ??
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#                        clientId: $
#                        clientSecret: $
#            scope:
#              - email
#              - profile

#aws:
#  paramstore:
#    enabled: true
#    prefix: /spring-boot-aws
#    name: pre-029
#    profileSeparator: _

#server:
#  port: 8085
#  ssl:
#    key-store: classpath:localhost.p12
#    key-store-type: PKCS12
#    key-store-password: changeit


#logging:
#  level:
#    org:
#      springframework:
#        orm:
#          jpa: DEBUG